# Don't change this! Version used to track needed updates.
version = 1
noItemSplatterOnDeath = true
noDeathItemDespawn = true
tryItemLavaSaveOnDeath = true
tryItemVoidSaveOnDeath = true
explosionResistantItems = true
playerDropMoreXpOnDeath = true
droppedExperiencePercent = 80
keepArmorOnDeath = false
armorDropList = [  ]
keepHotbarOnDeath = false
hotbarDropList = [  ]
keepAccessories = "LIST"
accessoryKeepList = [
    "minecraft:compass",
    "minecraft:clock"
]