name = "Dummydowned"
author = "kevBo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e0cb30a03511e449a60f8c2e682d0127f781cd14a93e2aea630f6503ea01582"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
