[common]
	#Reduced friction bonus for rail bedding, 1 to 10. 0 disables the bonus
	# Default: 8
	# Range: 0 ~ 10
	"rail bedding bonus" = 8
	#Reduced friction bonus for waxed carts, 1 to 10. 0 disables the bonus
	# Default: 0
	# Range: 0 ~ 10
	"waxy cart bonus" = 0
