	#Setting these values to false will disable features using the vanilla isEnabled method
	#It is recommended to create a new world after changing the config!
	["Kaleidoscopic Config".Features]
		#Enables Dyed Rock blocks
		dyedRockBlocks = true
		#Enables Dyed Rock block variants
		dyedRockVariantBlocks = true
		#Enables Dyed Ladders!
		dyedLadders = true
		#Enables Dyed Doors!
		dyedDoors = true
		#Enables Dyed Trapdoors!
		dyedTrapdoors = true
