[fog_modifiers]
	#If any custom fog modifiers are enabled
	fogModifiers = false
	#If the caves biome fog modifier is enabled
	cavesBiomeFogModifier = true
	#If the deep dark fog modifier is enabled
	deepDarkFogModifier = true
	#If the foggy biome fog modifier is enabled
	foggyBiomeFogModifier = true
